### ISSUE TITLE
Multi_rating script doesn't work 

### ISSUE THREAD

**Issue by MrDindows** [yak1ex/cf_userjs#6]
Multi_rating script doesn't work now because of removing "content" div.
This may be fixed by replacing 194 line:
```javascript
var e = document.getElementById('content').getElementsByTagName('script');
```
with:
```javascript
var e = document.getElementsByTagName('script');
```

**Comment by yak1ex** [comment]
Thanks. It seems that "content" is replaced by "pageContent" I'll fix it soon.
